GO

DROP TABLE IF EXISTS T_Product
DROP TABLE IF EXISTS T_ProductBrand
DROP TABLE IF EXISTS T_ProductType
DROP DATABASE IF EXISTS DB_E_Commerce

GO

CREATE DATABASE DB_E_Commerce

GO

USE DB_E_Commerce

GO 

CREATE TABLE T_ProductBrand(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL
);

CREATE TABLE T_ProductType(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL
);

CREATE TABLE T_Product(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	Price DOUBLE PRECISION NOT NULL,
	PicturePath NVARCHAR(300),
	ProductTypeId INT NOT NULL,
	ProductBrandId INT NOT NULL,
	FOREIGN KEY (ProductTypeId) REFERENCES T_ProductBrand(Id),
	FOREIGN KEY (ProductBrandId) REFERENCES T_ProductType(Id)
);